# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
